# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f59007ed208fb5718af4b0a78ec5268f69ba82937d99d79ed9673f8f3130e40403baa7568958ca021d2c02af53582478eb64b4ac1533f87e7e979f7f7809deca

test:
  secret_key_base: 7e9dc4b5c67e073b35039d69436d22479a9abd2c79c227aefe0c593bde7e8334e2564ff65700e012b90ec64bef76b5fd990dd403503ab58deadb0d68d560c11d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
